// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageV2.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MessageV2_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MessageV2_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MessageV2_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MessageV2_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MessageV2_2eproto;
namespace secmng {
namespace v2 {
class EncryptedMessage;
class EncryptedMessageDefaultTypeInternal;
extern EncryptedMessageDefaultTypeInternal _EncryptedMessage_default_instance_;
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class RequestPacket;
class RequestPacketDefaultTypeInternal;
extern RequestPacketDefaultTypeInternal _RequestPacket_default_instance_;
class ResponsePacket;
class ResponsePacketDefaultTypeInternal;
extern ResponsePacketDefaultTypeInternal _ResponsePacket_default_instance_;
class SendMessageRequest;
class SendMessageRequestDefaultTypeInternal;
extern SendMessageRequestDefaultTypeInternal _SendMessageRequest_default_instance_;
class SendMessageResponse;
class SendMessageResponseDefaultTypeInternal;
extern SendMessageResponseDefaultTypeInternal _SendMessageResponse_default_instance_;
}  // namespace v2
}  // namespace secmng
PROTOBUF_NAMESPACE_OPEN
template<> ::secmng::v2::EncryptedMessage* Arena::CreateMaybeMessage<::secmng::v2::EncryptedMessage>(Arena*);
template<> ::secmng::v2::Header* Arena::CreateMaybeMessage<::secmng::v2::Header>(Arena*);
template<> ::secmng::v2::RequestPacket* Arena::CreateMaybeMessage<::secmng::v2::RequestPacket>(Arena*);
template<> ::secmng::v2::ResponsePacket* Arena::CreateMaybeMessage<::secmng::v2::ResponsePacket>(Arena*);
template<> ::secmng::v2::SendMessageRequest* Arena::CreateMaybeMessage<::secmng::v2::SendMessageRequest>(Arena*);
template<> ::secmng::v2::SendMessageResponse* Arena::CreateMaybeMessage<::secmng::v2::SendMessageResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace secmng {
namespace v2 {

enum CommandType : int {
  CMD_UNKNOWN = 0,
  CMD_SEND_MSG_REQ = 1,
  CMD_SEND_MSG_RESP = 2,
  CommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  CommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool CommandType_IsValid(int value);
constexpr CommandType CommandType_MIN = CMD_UNKNOWN;
constexpr CommandType CommandType_MAX = CMD_SEND_MSG_RESP;
constexpr int CommandType_ARRAYSIZE = CommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandType_descriptor();
template<typename T>
inline const std::string& CommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CommandType_descriptor(), enum_t_value);
}
inline bool CommandType_Parse(
    const std::string& name, CommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CommandType>(
    CommandType_descriptor(), name, value);
}
enum ResultCode : int {
  RESULT_UNKNOWN = 0,
  RESULT_SUCCESS = 1,
  RESULT_FAILED = 2,
  RESULT_KEY_NOT_FOUND = 3,
  RESULT_KEY_INVALID = 4,
  RESULT_DECRYPT_FAILED = 5,
  RESULT_INVALID_REQUEST = 6,
  ResultCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ResultCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ResultCode_IsValid(int value);
constexpr ResultCode ResultCode_MIN = RESULT_UNKNOWN;
constexpr ResultCode ResultCode_MAX = RESULT_INVALID_REQUEST;
constexpr int ResultCode_ARRAYSIZE = ResultCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResultCode_descriptor();
template<typename T>
inline const std::string& ResultCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResultCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResultCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResultCode_descriptor(), enum_t_value);
}
inline bool ResultCode_Parse(
    const std::string& name, ResultCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResultCode>(
    ResultCode_descriptor(), name, value);
}
enum MessageType : int {
  MSG_TYPE_UNKNOWN = 0,
  MSG_TYPE_TEXT = 1,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = MSG_TYPE_UNKNOWN;
constexpr MessageType MessageType_MAX = MSG_TYPE_TEXT;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    const std::string& name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Header :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:secmng.v2.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Header* other);
  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(nullptr);
  }

  Header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Header* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "secmng.v2.Header";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MessageV2_2eproto);
    return ::descriptor_table_MessageV2_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message_id = 1;
  void clear_message_id();
  static const int kMessageIdFieldNumber = 1;
  const std::string& message_id() const;
  void set_message_id(const std::string& value);
  void set_message_id(std::string&& value);
  void set_message_id(const char* value);
  void set_message_id(const char* value, size_t size);
  std::string* mutable_message_id();
  std::string* release_message_id();
  void set_allocated_message_id(std::string* message_id);

  // string sender_id = 3;
  void clear_sender_id();
  static const int kSenderIdFieldNumber = 3;
  const std::string& sender_id() const;
  void set_sender_id(const std::string& value);
  void set_sender_id(std::string&& value);
  void set_sender_id(const char* value);
  void set_sender_id(const char* value, size_t size);
  std::string* mutable_sender_id();
  std::string* release_sender_id();
  void set_allocated_sender_id(std::string* sender_id);

  // string receiver_id = 4;
  void clear_receiver_id();
  static const int kReceiverIdFieldNumber = 4;
  const std::string& receiver_id() const;
  void set_receiver_id(const std::string& value);
  void set_receiver_id(std::string&& value);
  void set_receiver_id(const char* value);
  void set_receiver_id(const char* value, size_t size);
  std::string* mutable_receiver_id();
  std::string* release_receiver_id();
  void set_allocated_receiver_id(std::string* receiver_id);

  // int64 timestamp = 5;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 5;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);

  // .secmng.v2.CommandType command = 2;
  void clear_command();
  static const int kCommandFieldNumber = 2;
  ::secmng::v2::CommandType command() const;
  void set_command(::secmng::v2::CommandType value);

  // @@protoc_insertion_point(class_scope:secmng.v2.Header)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr receiver_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  int command_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MessageV2_2eproto;
};
// -------------------------------------------------------------------

class EncryptedMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:secmng.v2.EncryptedMessage) */ {
 public:
  EncryptedMessage();
  virtual ~EncryptedMessage();

  EncryptedMessage(const EncryptedMessage& from);
  EncryptedMessage(EncryptedMessage&& from) noexcept
    : EncryptedMessage() {
    *this = ::std::move(from);
  }

  inline EncryptedMessage& operator=(const EncryptedMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline EncryptedMessage& operator=(EncryptedMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EncryptedMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EncryptedMessage* internal_default_instance() {
    return reinterpret_cast<const EncryptedMessage*>(
               &_EncryptedMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(EncryptedMessage* other);
  friend void swap(EncryptedMessage& a, EncryptedMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EncryptedMessage* New() const final {
    return CreateMaybeMessage<EncryptedMessage>(nullptr);
  }

  EncryptedMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EncryptedMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EncryptedMessage& from);
  void MergeFrom(const EncryptedMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EncryptedMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "secmng.v2.EncryptedMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MessageV2_2eproto);
    return ::descriptor_table_MessageV2_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ciphertext = 3;
  void clear_ciphertext();
  static const int kCiphertextFieldNumber = 3;
  const std::string& ciphertext() const;
  void set_ciphertext(const std::string& value);
  void set_ciphertext(std::string&& value);
  void set_ciphertext(const char* value);
  void set_ciphertext(const char* value, size_t size);
  std::string* mutable_ciphertext();
  std::string* release_ciphertext();
  void set_allocated_ciphertext(std::string* ciphertext);

  // string nonce = 4;
  void clear_nonce();
  static const int kNonceFieldNumber = 4;
  const std::string& nonce() const;
  void set_nonce(const std::string& value);
  void set_nonce(std::string&& value);
  void set_nonce(const char* value);
  void set_nonce(const char* value, size_t size);
  std::string* mutable_nonce();
  std::string* release_nonce();
  void set_allocated_nonce(std::string* nonce);

  // string tag = 5;
  void clear_tag();
  static const int kTagFieldNumber = 5;
  const std::string& tag() const;
  void set_tag(const std::string& value);
  void set_tag(std::string&& value);
  void set_tag(const char* value);
  void set_tag(const char* value, size_t size);
  std::string* mutable_tag();
  std::string* release_tag();
  void set_allocated_tag(std::string* tag);

  // string algorithm = 6;
  void clear_algorithm();
  static const int kAlgorithmFieldNumber = 6;
  const std::string& algorithm() const;
  void set_algorithm(const std::string& value);
  void set_algorithm(std::string&& value);
  void set_algorithm(const char* value);
  void set_algorithm(const char* value, size_t size);
  std::string* mutable_algorithm();
  std::string* release_algorithm();
  void set_allocated_algorithm(std::string* algorithm);

  // int32 key_id = 1;
  void clear_key_id();
  static const int kKeyIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 key_id() const;
  void set_key_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // .secmng.v2.MessageType msg_type = 2;
  void clear_msg_type();
  static const int kMsgTypeFieldNumber = 2;
  ::secmng::v2::MessageType msg_type() const;
  void set_msg_type(::secmng::v2::MessageType value);

  // @@protoc_insertion_point(class_scope:secmng.v2.EncryptedMessage)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ciphertext_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nonce_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tag_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr algorithm_;
  ::PROTOBUF_NAMESPACE_ID::int32 key_id_;
  int msg_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MessageV2_2eproto;
};
// -------------------------------------------------------------------

class SendMessageRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:secmng.v2.SendMessageRequest) */ {
 public:
  SendMessageRequest();
  virtual ~SendMessageRequest();

  SendMessageRequest(const SendMessageRequest& from);
  SendMessageRequest(SendMessageRequest&& from) noexcept
    : SendMessageRequest() {
    *this = ::std::move(from);
  }

  inline SendMessageRequest& operator=(const SendMessageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendMessageRequest& operator=(SendMessageRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SendMessageRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SendMessageRequest* internal_default_instance() {
    return reinterpret_cast<const SendMessageRequest*>(
               &_SendMessageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SendMessageRequest* other);
  friend void swap(SendMessageRequest& a, SendMessageRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SendMessageRequest* New() const final {
    return CreateMaybeMessage<SendMessageRequest>(nullptr);
  }

  SendMessageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SendMessageRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SendMessageRequest& from);
  void MergeFrom(const SendMessageRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendMessageRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "secmng.v2.SendMessageRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MessageV2_2eproto);
    return ::descriptor_table_MessageV2_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .secmng.v2.EncryptedMessage message = 1;
  bool has_message() const;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::secmng::v2::EncryptedMessage& message() const;
  ::secmng::v2::EncryptedMessage* release_message();
  ::secmng::v2::EncryptedMessage* mutable_message();
  void set_allocated_message(::secmng::v2::EncryptedMessage* message);

  // @@protoc_insertion_point(class_scope:secmng.v2.SendMessageRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::secmng::v2::EncryptedMessage* message_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MessageV2_2eproto;
};
// -------------------------------------------------------------------

class SendMessageResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:secmng.v2.SendMessageResponse) */ {
 public:
  SendMessageResponse();
  virtual ~SendMessageResponse();

  SendMessageResponse(const SendMessageResponse& from);
  SendMessageResponse(SendMessageResponse&& from) noexcept
    : SendMessageResponse() {
    *this = ::std::move(from);
  }

  inline SendMessageResponse& operator=(const SendMessageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendMessageResponse& operator=(SendMessageResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SendMessageResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SendMessageResponse* internal_default_instance() {
    return reinterpret_cast<const SendMessageResponse*>(
               &_SendMessageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(SendMessageResponse* other);
  friend void swap(SendMessageResponse& a, SendMessageResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SendMessageResponse* New() const final {
    return CreateMaybeMessage<SendMessageResponse>(nullptr);
  }

  SendMessageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SendMessageResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SendMessageResponse& from);
  void MergeFrom(const SendMessageResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendMessageResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "secmng.v2.SendMessageResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MessageV2_2eproto);
    return ::descriptor_table_MessageV2_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);

  // string server_message_id = 3;
  void clear_server_message_id();
  static const int kServerMessageIdFieldNumber = 3;
  const std::string& server_message_id() const;
  void set_server_message_id(const std::string& value);
  void set_server_message_id(std::string&& value);
  void set_server_message_id(const char* value);
  void set_server_message_id(const char* value, size_t size);
  std::string* mutable_server_message_id();
  std::string* release_server_message_id();
  void set_allocated_server_message_id(std::string* server_message_id);

  // int64 server_time = 4;
  void clear_server_time();
  static const int kServerTimeFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int64 server_time() const;
  void set_server_time(::PROTOBUF_NAMESPACE_ID::int64 value);

  // .secmng.v2.ResultCode code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::secmng::v2::ResultCode code() const;
  void set_code(::secmng::v2::ResultCode value);

  // @@protoc_insertion_point(class_scope:secmng.v2.SendMessageResponse)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr server_message_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 server_time_;
  int code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MessageV2_2eproto;
};
// -------------------------------------------------------------------

class RequestPacket :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:secmng.v2.RequestPacket) */ {
 public:
  RequestPacket();
  virtual ~RequestPacket();

  RequestPacket(const RequestPacket& from);
  RequestPacket(RequestPacket&& from) noexcept
    : RequestPacket() {
    *this = ::std::move(from);
  }

  inline RequestPacket& operator=(const RequestPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestPacket& operator=(RequestPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RequestPacket& default_instance();

  enum BodyCase {
    kSendMsgReq = 2,
    BODY_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestPacket* internal_default_instance() {
    return reinterpret_cast<const RequestPacket*>(
               &_RequestPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(RequestPacket* other);
  friend void swap(RequestPacket& a, RequestPacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RequestPacket* New() const final {
    return CreateMaybeMessage<RequestPacket>(nullptr);
  }

  RequestPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RequestPacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RequestPacket& from);
  void MergeFrom(const RequestPacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestPacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "secmng.v2.RequestPacket";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MessageV2_2eproto);
    return ::descriptor_table_MessageV2_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .secmng.v2.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::secmng::v2::Header& header() const;
  ::secmng::v2::Header* release_header();
  ::secmng::v2::Header* mutable_header();
  void set_allocated_header(::secmng::v2::Header* header);

  // .secmng.v2.SendMessageRequest send_msg_req = 2;
  bool has_send_msg_req() const;
  void clear_send_msg_req();
  static const int kSendMsgReqFieldNumber = 2;
  const ::secmng::v2::SendMessageRequest& send_msg_req() const;
  ::secmng::v2::SendMessageRequest* release_send_msg_req();
  ::secmng::v2::SendMessageRequest* mutable_send_msg_req();
  void set_allocated_send_msg_req(::secmng::v2::SendMessageRequest* send_msg_req);

  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:secmng.v2.RequestPacket)
 private:
  class HasBitSetters;
  void set_has_send_msg_req();

  inline bool has_body() const;
  inline void clear_has_body();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::secmng::v2::Header* header_;
  union BodyUnion {
    BodyUnion() {}
    ::secmng::v2::SendMessageRequest* send_msg_req_;
  } body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_MessageV2_2eproto;
};
// -------------------------------------------------------------------

class ResponsePacket :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:secmng.v2.ResponsePacket) */ {
 public:
  ResponsePacket();
  virtual ~ResponsePacket();

  ResponsePacket(const ResponsePacket& from);
  ResponsePacket(ResponsePacket&& from) noexcept
    : ResponsePacket() {
    *this = ::std::move(from);
  }

  inline ResponsePacket& operator=(const ResponsePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponsePacket& operator=(ResponsePacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResponsePacket& default_instance();

  enum BodyCase {
    kSendMsgResp = 2,
    BODY_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponsePacket* internal_default_instance() {
    return reinterpret_cast<const ResponsePacket*>(
               &_ResponsePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ResponsePacket* other);
  friend void swap(ResponsePacket& a, ResponsePacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResponsePacket* New() const final {
    return CreateMaybeMessage<ResponsePacket>(nullptr);
  }

  ResponsePacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResponsePacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResponsePacket& from);
  void MergeFrom(const ResponsePacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponsePacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "secmng.v2.ResponsePacket";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MessageV2_2eproto);
    return ::descriptor_table_MessageV2_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .secmng.v2.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::secmng::v2::Header& header() const;
  ::secmng::v2::Header* release_header();
  ::secmng::v2::Header* mutable_header();
  void set_allocated_header(::secmng::v2::Header* header);

  // .secmng.v2.SendMessageResponse send_msg_resp = 2;
  bool has_send_msg_resp() const;
  void clear_send_msg_resp();
  static const int kSendMsgRespFieldNumber = 2;
  const ::secmng::v2::SendMessageResponse& send_msg_resp() const;
  ::secmng::v2::SendMessageResponse* release_send_msg_resp();
  ::secmng::v2::SendMessageResponse* mutable_send_msg_resp();
  void set_allocated_send_msg_resp(::secmng::v2::SendMessageResponse* send_msg_resp);

  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:secmng.v2.ResponsePacket)
 private:
  class HasBitSetters;
  void set_has_send_msg_resp();

  inline bool has_body() const;
  inline void clear_has_body();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::secmng::v2::Header* header_;
  union BodyUnion {
    BodyUnion() {}
    ::secmng::v2::SendMessageResponse* send_msg_resp_;
  } body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_MessageV2_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Header

// string message_id = 1;
inline void Header::clear_message_id() {
  message_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Header::message_id() const {
  // @@protoc_insertion_point(field_get:secmng.v2.Header.message_id)
  return message_id_.GetNoArena();
}
inline void Header::set_message_id(const std::string& value) {
  
  message_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.Header.message_id)
}
inline void Header::set_message_id(std::string&& value) {
  
  message_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.Header.message_id)
}
inline void Header::set_message_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.Header.message_id)
}
inline void Header::set_message_id(const char* value, size_t size) {
  
  message_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.Header.message_id)
}
inline std::string* Header::mutable_message_id() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.Header.message_id)
  return message_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Header::release_message_id() {
  // @@protoc_insertion_point(field_release:secmng.v2.Header.message_id)
  
  return message_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_message_id(std::string* message_id) {
  if (message_id != nullptr) {
    
  } else {
    
  }
  message_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message_id);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.Header.message_id)
}

// .secmng.v2.CommandType command = 2;
inline void Header::clear_command() {
  command_ = 0;
}
inline ::secmng::v2::CommandType Header::command() const {
  // @@protoc_insertion_point(field_get:secmng.v2.Header.command)
  return static_cast< ::secmng::v2::CommandType >(command_);
}
inline void Header::set_command(::secmng::v2::CommandType value) {
  
  command_ = value;
  // @@protoc_insertion_point(field_set:secmng.v2.Header.command)
}

// string sender_id = 3;
inline void Header::clear_sender_id() {
  sender_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Header::sender_id() const {
  // @@protoc_insertion_point(field_get:secmng.v2.Header.sender_id)
  return sender_id_.GetNoArena();
}
inline void Header::set_sender_id(const std::string& value) {
  
  sender_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.Header.sender_id)
}
inline void Header::set_sender_id(std::string&& value) {
  
  sender_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.Header.sender_id)
}
inline void Header::set_sender_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sender_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.Header.sender_id)
}
inline void Header::set_sender_id(const char* value, size_t size) {
  
  sender_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.Header.sender_id)
}
inline std::string* Header::mutable_sender_id() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.Header.sender_id)
  return sender_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Header::release_sender_id() {
  // @@protoc_insertion_point(field_release:secmng.v2.Header.sender_id)
  
  return sender_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_sender_id(std::string* sender_id) {
  if (sender_id != nullptr) {
    
  } else {
    
  }
  sender_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sender_id);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.Header.sender_id)
}

// string receiver_id = 4;
inline void Header::clear_receiver_id() {
  receiver_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Header::receiver_id() const {
  // @@protoc_insertion_point(field_get:secmng.v2.Header.receiver_id)
  return receiver_id_.GetNoArena();
}
inline void Header::set_receiver_id(const std::string& value) {
  
  receiver_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.Header.receiver_id)
}
inline void Header::set_receiver_id(std::string&& value) {
  
  receiver_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.Header.receiver_id)
}
inline void Header::set_receiver_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  receiver_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.Header.receiver_id)
}
inline void Header::set_receiver_id(const char* value, size_t size) {
  
  receiver_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.Header.receiver_id)
}
inline std::string* Header::mutable_receiver_id() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.Header.receiver_id)
  return receiver_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Header::release_receiver_id() {
  // @@protoc_insertion_point(field_release:secmng.v2.Header.receiver_id)
  
  return receiver_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_receiver_id(std::string* receiver_id) {
  if (receiver_id != nullptr) {
    
  } else {
    
  }
  receiver_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), receiver_id);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.Header.receiver_id)
}

// int64 timestamp = 5;
inline void Header::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Header::timestamp() const {
  // @@protoc_insertion_point(field_get:secmng.v2.Header.timestamp)
  return timestamp_;
}
inline void Header::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:secmng.v2.Header.timestamp)
}

// -------------------------------------------------------------------

// EncryptedMessage

// int32 key_id = 1;
inline void EncryptedMessage::clear_key_id() {
  key_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EncryptedMessage::key_id() const {
  // @@protoc_insertion_point(field_get:secmng.v2.EncryptedMessage.key_id)
  return key_id_;
}
inline void EncryptedMessage::set_key_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  key_id_ = value;
  // @@protoc_insertion_point(field_set:secmng.v2.EncryptedMessage.key_id)
}

// .secmng.v2.MessageType msg_type = 2;
inline void EncryptedMessage::clear_msg_type() {
  msg_type_ = 0;
}
inline ::secmng::v2::MessageType EncryptedMessage::msg_type() const {
  // @@protoc_insertion_point(field_get:secmng.v2.EncryptedMessage.msg_type)
  return static_cast< ::secmng::v2::MessageType >(msg_type_);
}
inline void EncryptedMessage::set_msg_type(::secmng::v2::MessageType value) {
  
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:secmng.v2.EncryptedMessage.msg_type)
}

// string ciphertext = 3;
inline void EncryptedMessage::clear_ciphertext() {
  ciphertext_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EncryptedMessage::ciphertext() const {
  // @@protoc_insertion_point(field_get:secmng.v2.EncryptedMessage.ciphertext)
  return ciphertext_.GetNoArena();
}
inline void EncryptedMessage::set_ciphertext(const std::string& value) {
  
  ciphertext_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.EncryptedMessage.ciphertext)
}
inline void EncryptedMessage::set_ciphertext(std::string&& value) {
  
  ciphertext_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.EncryptedMessage.ciphertext)
}
inline void EncryptedMessage::set_ciphertext(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ciphertext_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.EncryptedMessage.ciphertext)
}
inline void EncryptedMessage::set_ciphertext(const char* value, size_t size) {
  
  ciphertext_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.EncryptedMessage.ciphertext)
}
inline std::string* EncryptedMessage::mutable_ciphertext() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.EncryptedMessage.ciphertext)
  return ciphertext_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EncryptedMessage::release_ciphertext() {
  // @@protoc_insertion_point(field_release:secmng.v2.EncryptedMessage.ciphertext)
  
  return ciphertext_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EncryptedMessage::set_allocated_ciphertext(std::string* ciphertext) {
  if (ciphertext != nullptr) {
    
  } else {
    
  }
  ciphertext_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ciphertext);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.EncryptedMessage.ciphertext)
}

// string nonce = 4;
inline void EncryptedMessage::clear_nonce() {
  nonce_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EncryptedMessage::nonce() const {
  // @@protoc_insertion_point(field_get:secmng.v2.EncryptedMessage.nonce)
  return nonce_.GetNoArena();
}
inline void EncryptedMessage::set_nonce(const std::string& value) {
  
  nonce_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.EncryptedMessage.nonce)
}
inline void EncryptedMessage::set_nonce(std::string&& value) {
  
  nonce_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.EncryptedMessage.nonce)
}
inline void EncryptedMessage::set_nonce(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  nonce_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.EncryptedMessage.nonce)
}
inline void EncryptedMessage::set_nonce(const char* value, size_t size) {
  
  nonce_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.EncryptedMessage.nonce)
}
inline std::string* EncryptedMessage::mutable_nonce() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.EncryptedMessage.nonce)
  return nonce_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EncryptedMessage::release_nonce() {
  // @@protoc_insertion_point(field_release:secmng.v2.EncryptedMessage.nonce)
  
  return nonce_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EncryptedMessage::set_allocated_nonce(std::string* nonce) {
  if (nonce != nullptr) {
    
  } else {
    
  }
  nonce_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nonce);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.EncryptedMessage.nonce)
}

// string tag = 5;
inline void EncryptedMessage::clear_tag() {
  tag_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EncryptedMessage::tag() const {
  // @@protoc_insertion_point(field_get:secmng.v2.EncryptedMessage.tag)
  return tag_.GetNoArena();
}
inline void EncryptedMessage::set_tag(const std::string& value) {
  
  tag_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.EncryptedMessage.tag)
}
inline void EncryptedMessage::set_tag(std::string&& value) {
  
  tag_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.EncryptedMessage.tag)
}
inline void EncryptedMessage::set_tag(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tag_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.EncryptedMessage.tag)
}
inline void EncryptedMessage::set_tag(const char* value, size_t size) {
  
  tag_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.EncryptedMessage.tag)
}
inline std::string* EncryptedMessage::mutable_tag() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.EncryptedMessage.tag)
  return tag_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EncryptedMessage::release_tag() {
  // @@protoc_insertion_point(field_release:secmng.v2.EncryptedMessage.tag)
  
  return tag_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EncryptedMessage::set_allocated_tag(std::string* tag) {
  if (tag != nullptr) {
    
  } else {
    
  }
  tag_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tag);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.EncryptedMessage.tag)
}

// string algorithm = 6;
inline void EncryptedMessage::clear_algorithm() {
  algorithm_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EncryptedMessage::algorithm() const {
  // @@protoc_insertion_point(field_get:secmng.v2.EncryptedMessage.algorithm)
  return algorithm_.GetNoArena();
}
inline void EncryptedMessage::set_algorithm(const std::string& value) {
  
  algorithm_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.EncryptedMessage.algorithm)
}
inline void EncryptedMessage::set_algorithm(std::string&& value) {
  
  algorithm_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.EncryptedMessage.algorithm)
}
inline void EncryptedMessage::set_algorithm(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  algorithm_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.EncryptedMessage.algorithm)
}
inline void EncryptedMessage::set_algorithm(const char* value, size_t size) {
  
  algorithm_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.EncryptedMessage.algorithm)
}
inline std::string* EncryptedMessage::mutable_algorithm() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.EncryptedMessage.algorithm)
  return algorithm_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EncryptedMessage::release_algorithm() {
  // @@protoc_insertion_point(field_release:secmng.v2.EncryptedMessage.algorithm)
  
  return algorithm_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EncryptedMessage::set_allocated_algorithm(std::string* algorithm) {
  if (algorithm != nullptr) {
    
  } else {
    
  }
  algorithm_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), algorithm);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.EncryptedMessage.algorithm)
}

// -------------------------------------------------------------------

// SendMessageRequest

// .secmng.v2.EncryptedMessage message = 1;
inline bool SendMessageRequest::has_message() const {
  return this != internal_default_instance() && message_ != nullptr;
}
inline void SendMessageRequest::clear_message() {
  if (GetArenaNoVirtual() == nullptr && message_ != nullptr) {
    delete message_;
  }
  message_ = nullptr;
}
inline const ::secmng::v2::EncryptedMessage& SendMessageRequest::message() const {
  const ::secmng::v2::EncryptedMessage* p = message_;
  // @@protoc_insertion_point(field_get:secmng.v2.SendMessageRequest.message)
  return p != nullptr ? *p : *reinterpret_cast<const ::secmng::v2::EncryptedMessage*>(
      &::secmng::v2::_EncryptedMessage_default_instance_);
}
inline ::secmng::v2::EncryptedMessage* SendMessageRequest::release_message() {
  // @@protoc_insertion_point(field_release:secmng.v2.SendMessageRequest.message)
  
  ::secmng::v2::EncryptedMessage* temp = message_;
  message_ = nullptr;
  return temp;
}
inline ::secmng::v2::EncryptedMessage* SendMessageRequest::mutable_message() {
  
  if (message_ == nullptr) {
    auto* p = CreateMaybeMessage<::secmng::v2::EncryptedMessage>(GetArenaNoVirtual());
    message_ = p;
  }
  // @@protoc_insertion_point(field_mutable:secmng.v2.SendMessageRequest.message)
  return message_;
}
inline void SendMessageRequest::set_allocated_message(::secmng::v2::EncryptedMessage* message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete message_;
  }
  if (message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message, submessage_arena);
    }
    
  } else {
    
  }
  message_ = message;
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.SendMessageRequest.message)
}

// -------------------------------------------------------------------

// SendMessageResponse

// .secmng.v2.ResultCode code = 1;
inline void SendMessageResponse::clear_code() {
  code_ = 0;
}
inline ::secmng::v2::ResultCode SendMessageResponse::code() const {
  // @@protoc_insertion_point(field_get:secmng.v2.SendMessageResponse.code)
  return static_cast< ::secmng::v2::ResultCode >(code_);
}
inline void SendMessageResponse::set_code(::secmng::v2::ResultCode value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:secmng.v2.SendMessageResponse.code)
}

// string message = 2;
inline void SendMessageResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SendMessageResponse::message() const {
  // @@protoc_insertion_point(field_get:secmng.v2.SendMessageResponse.message)
  return message_.GetNoArena();
}
inline void SendMessageResponse::set_message(const std::string& value) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.SendMessageResponse.message)
}
inline void SendMessageResponse::set_message(std::string&& value) {
  
  message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.SendMessageResponse.message)
}
inline void SendMessageResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.SendMessageResponse.message)
}
inline void SendMessageResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.SendMessageResponse.message)
}
inline std::string* SendMessageResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.SendMessageResponse.message)
  return message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SendMessageResponse::release_message() {
  // @@protoc_insertion_point(field_release:secmng.v2.SendMessageResponse.message)
  
  return message_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SendMessageResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.SendMessageResponse.message)
}

// string server_message_id = 3;
inline void SendMessageResponse::clear_server_message_id() {
  server_message_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SendMessageResponse::server_message_id() const {
  // @@protoc_insertion_point(field_get:secmng.v2.SendMessageResponse.server_message_id)
  return server_message_id_.GetNoArena();
}
inline void SendMessageResponse::set_server_message_id(const std::string& value) {
  
  server_message_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:secmng.v2.SendMessageResponse.server_message_id)
}
inline void SendMessageResponse::set_server_message_id(std::string&& value) {
  
  server_message_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:secmng.v2.SendMessageResponse.server_message_id)
}
inline void SendMessageResponse::set_server_message_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  server_message_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:secmng.v2.SendMessageResponse.server_message_id)
}
inline void SendMessageResponse::set_server_message_id(const char* value, size_t size) {
  
  server_message_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:secmng.v2.SendMessageResponse.server_message_id)
}
inline std::string* SendMessageResponse::mutable_server_message_id() {
  
  // @@protoc_insertion_point(field_mutable:secmng.v2.SendMessageResponse.server_message_id)
  return server_message_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SendMessageResponse::release_server_message_id() {
  // @@protoc_insertion_point(field_release:secmng.v2.SendMessageResponse.server_message_id)
  
  return server_message_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SendMessageResponse::set_allocated_server_message_id(std::string* server_message_id) {
  if (server_message_id != nullptr) {
    
  } else {
    
  }
  server_message_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), server_message_id);
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.SendMessageResponse.server_message_id)
}

// int64 server_time = 4;
inline void SendMessageResponse::clear_server_time() {
  server_time_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 SendMessageResponse::server_time() const {
  // @@protoc_insertion_point(field_get:secmng.v2.SendMessageResponse.server_time)
  return server_time_;
}
inline void SendMessageResponse::set_server_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  server_time_ = value;
  // @@protoc_insertion_point(field_set:secmng.v2.SendMessageResponse.server_time)
}

// -------------------------------------------------------------------

// RequestPacket

// .secmng.v2.Header header = 1;
inline bool RequestPacket::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline void RequestPacket::clear_header() {
  if (GetArenaNoVirtual() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::secmng::v2::Header& RequestPacket::header() const {
  const ::secmng::v2::Header* p = header_;
  // @@protoc_insertion_point(field_get:secmng.v2.RequestPacket.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::secmng::v2::Header*>(
      &::secmng::v2::_Header_default_instance_);
}
inline ::secmng::v2::Header* RequestPacket::release_header() {
  // @@protoc_insertion_point(field_release:secmng.v2.RequestPacket.header)
  
  ::secmng::v2::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::secmng::v2::Header* RequestPacket::mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::secmng::v2::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:secmng.v2.RequestPacket.header)
  return header_;
}
inline void RequestPacket::set_allocated_header(::secmng::v2::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.RequestPacket.header)
}

// .secmng.v2.SendMessageRequest send_msg_req = 2;
inline bool RequestPacket::has_send_msg_req() const {
  return body_case() == kSendMsgReq;
}
inline void RequestPacket::set_has_send_msg_req() {
  _oneof_case_[0] = kSendMsgReq;
}
inline void RequestPacket::clear_send_msg_req() {
  if (has_send_msg_req()) {
    delete body_.send_msg_req_;
    clear_has_body();
  }
}
inline ::secmng::v2::SendMessageRequest* RequestPacket::release_send_msg_req() {
  // @@protoc_insertion_point(field_release:secmng.v2.RequestPacket.send_msg_req)
  if (has_send_msg_req()) {
    clear_has_body();
      ::secmng::v2::SendMessageRequest* temp = body_.send_msg_req_;
    body_.send_msg_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::secmng::v2::SendMessageRequest& RequestPacket::send_msg_req() const {
  // @@protoc_insertion_point(field_get:secmng.v2.RequestPacket.send_msg_req)
  return has_send_msg_req()
      ? *body_.send_msg_req_
      : *reinterpret_cast< ::secmng::v2::SendMessageRequest*>(&::secmng::v2::_SendMessageRequest_default_instance_);
}
inline ::secmng::v2::SendMessageRequest* RequestPacket::mutable_send_msg_req() {
  if (!has_send_msg_req()) {
    clear_body();
    set_has_send_msg_req();
    body_.send_msg_req_ = CreateMaybeMessage< ::secmng::v2::SendMessageRequest >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:secmng.v2.RequestPacket.send_msg_req)
  return body_.send_msg_req_;
}

inline bool RequestPacket::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void RequestPacket::clear_has_body() {
  _oneof_case_[0] = BODY_NOT_SET;
}
inline RequestPacket::BodyCase RequestPacket::body_case() const {
  return RequestPacket::BodyCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ResponsePacket

// .secmng.v2.Header header = 1;
inline bool ResponsePacket::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline void ResponsePacket::clear_header() {
  if (GetArenaNoVirtual() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::secmng::v2::Header& ResponsePacket::header() const {
  const ::secmng::v2::Header* p = header_;
  // @@protoc_insertion_point(field_get:secmng.v2.ResponsePacket.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::secmng::v2::Header*>(
      &::secmng::v2::_Header_default_instance_);
}
inline ::secmng::v2::Header* ResponsePacket::release_header() {
  // @@protoc_insertion_point(field_release:secmng.v2.ResponsePacket.header)
  
  ::secmng::v2::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::secmng::v2::Header* ResponsePacket::mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::secmng::v2::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:secmng.v2.ResponsePacket.header)
  return header_;
}
inline void ResponsePacket::set_allocated_header(::secmng::v2::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:secmng.v2.ResponsePacket.header)
}

// .secmng.v2.SendMessageResponse send_msg_resp = 2;
inline bool ResponsePacket::has_send_msg_resp() const {
  return body_case() == kSendMsgResp;
}
inline void ResponsePacket::set_has_send_msg_resp() {
  _oneof_case_[0] = kSendMsgResp;
}
inline void ResponsePacket::clear_send_msg_resp() {
  if (has_send_msg_resp()) {
    delete body_.send_msg_resp_;
    clear_has_body();
  }
}
inline ::secmng::v2::SendMessageResponse* ResponsePacket::release_send_msg_resp() {
  // @@protoc_insertion_point(field_release:secmng.v2.ResponsePacket.send_msg_resp)
  if (has_send_msg_resp()) {
    clear_has_body();
      ::secmng::v2::SendMessageResponse* temp = body_.send_msg_resp_;
    body_.send_msg_resp_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::secmng::v2::SendMessageResponse& ResponsePacket::send_msg_resp() const {
  // @@protoc_insertion_point(field_get:secmng.v2.ResponsePacket.send_msg_resp)
  return has_send_msg_resp()
      ? *body_.send_msg_resp_
      : *reinterpret_cast< ::secmng::v2::SendMessageResponse*>(&::secmng::v2::_SendMessageResponse_default_instance_);
}
inline ::secmng::v2::SendMessageResponse* ResponsePacket::mutable_send_msg_resp() {
  if (!has_send_msg_resp()) {
    clear_body();
    set_has_send_msg_resp();
    body_.send_msg_resp_ = CreateMaybeMessage< ::secmng::v2::SendMessageResponse >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:secmng.v2.ResponsePacket.send_msg_resp)
  return body_.send_msg_resp_;
}

inline bool ResponsePacket::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void ResponsePacket::clear_has_body() {
  _oneof_case_[0] = BODY_NOT_SET;
}
inline ResponsePacket::BodyCase ResponsePacket::body_case() const {
  return ResponsePacket::BodyCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace secmng

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::secmng::v2::CommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::secmng::v2::CommandType>() {
  return ::secmng::v2::CommandType_descriptor();
}
template <> struct is_proto_enum< ::secmng::v2::ResultCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::secmng::v2::ResultCode>() {
  return ::secmng::v2::ResultCode_descriptor();
}
template <> struct is_proto_enum< ::secmng::v2::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::secmng::v2::MessageType>() {
  return ::secmng::v2::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MessageV2_2eproto
